apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
  namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
#   namespace: default
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret
  annotations:
    kubernetes.io/service-account.name: deploy-robot
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #name: deploy-robot-role
  name: cluster-admin
  namespace: default
rules: 
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    # resourceNames: ["admin","edit","view","cluster-admin"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["deployments",
    "pods",
    "secrets",
    "serviceaccounts",
    "clusterroles",
    "clusterrolebindings",
    "statefulsets",
    "services",
    "configmaps", 
    "namespaces", "rbac.authorization.k8s.io/v1", "rbac.authorization.k8s.io"]
    # verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
    verbs: ["*"]
    # resourceNames: ["admin","edit","view","cluster-admin"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments",
    "pods",
    "secrets",
    "serviceaccounts",
    "clusterroles",
    "clusterrolebindings",
    "statefulsets",
    "services",
    "configmaps", "namespaces","rbac.authorization.k8s.io"]
    # verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
    verbs: ["*"]
    # resourceNames: ["admin","edit","view","cluster-admin"]
  - apiGroups: [""]
    resources: ["deployments",
    "pods",
    "secrets",
    "serviceaccounts",
    "clusterroles",
    "clusterrolebindings",
    "statefulsets",
    "services",
    "configmaps", "namespaces","rbac.authorization.k8s.io"]
    # verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
    verbs: ["*"]
    # resourceNames: ["admin","edit","view","cluster-admin"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: deploy-robot
    namespace: default
roleRef:
  kind: Role
  #name: deploy-robot-role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    #name: deploy-robot-role2
    name: cluster-admin
    # namespace: default
rules: 
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
    #   resourceNames: ["admin","edit","view","cluster-admin"]
    - apiGroups: ["rbac.authorization.k8s.io"]
      resources: ["deployments",
      "pods",
      "secrets",
      "serviceaccounts",
      "clusterroles",
      "clusterrolebindings",
      "statefulsets",
      "services",
      "configmaps", 
      "namespaces","rbac.authorization.k8s.io/v1","rbac.authorization.k8s.io"]
    #   verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
      verbs: ["*"]
    #   resourceNames: ["admin","edit","view","cluster-admin"]
    - apiGroups: ["apps", "extensions"]
      resources: ["deployments",
      "pods",
      "secrets",
      "serviceaccounts",
      "clusterroles",
      "clusterrolebindings",
      "statefulsets",
      "services",
      "configmaps", "namespaces","rbac.authorization.k8s.io"]
    #   verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
      verbs: ["*"]
    #   resourceNames: ["admin","edit","view","cluster-admin"]
    - apiGroups: [""]
      resources: ["deployments",
      "pods",
      "secrets",
      "serviceaccounts",
      "clusterroles",
      "clusterrolebindings",
      "statefulsets",
      "services",
      "configmaps", "namespaces","rbac.authorization.k8s.io"]
    #   verbs: ["patch", "create", "delete", "get", "list", "update", "bind"]
      verbs: ["*"]
    #   resourceNames: ["admin","edit","view","cluster-admin"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: global-rolebinding
    # namespace: default
subjects:
    - kind: ServiceAccount
      name: deploy-robot
      namespace: default
roleRef:
    kind: Role
    # name: deploy-robot-role2
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: clusterrolebinding
subjects:
- kind: ServiceAccount
  name: deploy-robot
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
---
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#     name: clusterrolebinding
# subjects:
# - kind: ServiceAccount
#   name: deploy-robot
#   # namespace: default
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: "rbac.authorization.k8s.io"